# Generated by Django 4.2.7 on 2023-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_llegada', models.DateField()),
                ('hora_llegada', models.TimeField()),
                ('fecha_salida', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('lugar_salida', models.CharField(max_length=100)),
                ('lugar_llegada', models.CharField(max_length=100)),
                ('cantidad_adultos', models.PositiveIntegerField()),
                ('cantidad_menores', models.PositiveIntegerField()),
                ('espacios_vigentes', models.PositiveIntegerField()),
            ],
        ),
    ]
