# Generated by Django 4.2.7 on 2023-12-02 20:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0002_viaje'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cupos',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='cantidad_adultos',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='cantidad_menores',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_adultos',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reserva',
            name='cantidad_menores',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='viaje',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='viaje',
            name='titulo',
            field=models.CharField(default='Untitled Trip', max_length=100),
        ),
    ]
