# Generated by Django 4.2.7 on 2023-12-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubai', '0003_remove_reserva_cupos_remove_viaje_cantidad_adultos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='titulo',
        ),
        migrations.AddField(
            model_name='viaje',
            name='destino',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
    ]
